logging:
  level:
    root: WARN
    org:
      spring: WARN
    io:
      kmachine: DEBUG

info:
  app:
    name: KMachine

kmachine:
  bootstrapServers: ${BOOTSTRAP_SERVERS:localhost:9092}
  zookeeperConnect: ${ZOOKEEPER_CONNECT:localhost:2181}
  verticesTopic: vertices
  edgesGroupedBySourceTopic: edges
  solutionSetTopic: solutionSet
  solutionSetStore: solutionStore
  workSetTopic: workSet
  numPartitions: 50
  replicationFactor: 1

management.endpoint.health.show-details: always
management.endpoints.web.exposure.include: '*'
